### ISSUE TITLE
Course about Github Actions

### ISSUE THREAD

**Issue by juliosaraiva** [LondonAppDeveloper/gh-actions-completed-code#2]
Hello Mark!

Are you thinking to create a course about Github Actions?, It'll be amazing. Very excited about that.

Best Regards
Julio

**Comment by LondonAppDev** [comment]
lol busted... 

Yes, we are planning to put out some content about it shortly. 

Then in the mid-term we're going to update this course to use GitHub Actions instead of Travis-CI: [Build a Backend REST API with Python & Django - Advanced](https://londonapp.dev/c2).

Is there any particular area of GitHub Actions you're interested in?

**Comment by juliosaraiva** [comment]
> lol busted...
> 
> Yes, we are planning to put out some content about it shortly.
> 
> Then in the mid-term we're going to update this course to use GitHub Actions instead of Travis-CI: [Build a Backend REST API with Python & Django - Advanced](https://londonapp.dev/c2).
> 
> Is there any particular area of GitHub Actions you're interested in?

Awesome! Thanks for answered.

I guess how to release an application using GH actions and also how to create my own actions.

I appreciate that.
